# Generated by Django 2.2.3 on 2019-07-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'book_data',
            },
        ),
        migrations.CreateModel(
            name='Librarians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
            ],
            options={
                'db_table': 'libr_data',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('libname', models.CharField(max_length=50)),
                ('landline', models.IntegerField()),
                ('librian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='insurance.Librarians')),
            ],
            options={
                'db_table': 'library_data',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('age', models.IntegerField()),
                ('books', models.ManyToManyField(to='insurance.Book')),
            ],
            options={
                'db_table': 'student_data',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Library'),
        ),
    ]
